[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts@4.8.3/=lib/openzeppelin-contracts-4.8.3/contracts/",
    "@openzeppelin/contracts@5.3.0/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@ccip/contracts/=lib/chainlink-ccip/chains/evm/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts/",
    "@chainlink-local/=lib/chainlink-local/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
arb-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
